---
# tasks file for oci-resources-by-type

- name: print type
  ansible.builtin.debug:
    msg: "{{ resource_type_item.name }}"

# - name: List compartments of tenancy
#   collections:
#     - oracle.oci
#   oci_identity_compartment_facts:
#     parent_compartment_id: "{{ tenancy_ocid }}"
#     access_level: ANY
#     compartment_id_in_subtree: true
#     lifecycle_state: "ACTIVE"
#   register: compartment_list_out

- name: Search resource type "{{ resource_type_item.name }}" by compartment
  include_tasks: oci-resource-search.yml
  loop: "{{ compartment_search }}"
  loop_control:
    loop_var: compartment_item
  when:
    - "compartment_item.search"

- name: Check "./output/{{ resource_type_item.name }}_{{ tenancy_region }}.csv"
  stat:
    path: "./output/{{ resource_type_item.name }}_{{ tenancy_region }}.csv"
  register: check_file

- name: Write down resources
  lineinfile:
    insertbefore: BOF
    dest: "./output/{{ resource_type_item.name }}_{{ tenancy_region }}.csv"
    line: "RESOURCE_TYPE;COMPARTMENT_NAME;RESOURCE_NAME;RESOURCE_OCID;COMPARTMENT_OCID"
  when: 
    - "check_file.stat.exists"
